### PR TITLE
Throw error on negative for range loop in gs

### LINKED ISSUE #141: Golfscript: range doesn't work properly with negatives
`for $b -15 1` compiles to `1,-15>` which obviously doesn't work.

### PR DESCRIPTION
**Pull request by MichalMarsalek**
This closes #141 by throwing an error when the form currently used doesn't work. Not sure what a best general fallback is.

### CODE REVIEW

File: src/languages/golfscript/emit.ts [hunk 1]
```diff
@@ -1,133 +1,146 @@
...
+              : [emitExpr(stmt.increment), "%"],
+            "{",
+            ":",
+            emitExpr(stmt.variable),
+            ";",
+            emitMultiExpr(stmt.body, stmt),
+            "}",
+            "%",
+          ];
+        throw new EmitError(stmt, "potentially negative");
```
Comment (MeWhenI) [inline src/languages/golfscript/emit.ts:52]:
```suggestion
        return [
          isNaturalType(stmt.low)
            ? [
                emitExpr(stmt.high),
                ",",
                isIntLiteral(stmt.low, 0n) ? [] : [emitExpr(stmt.low), ">"],
              ]
            : [
                emitExpr(stmt.high),
                emitExpr(stmt.low),
                "-",
                ",",
                "{",
                emitExpr(stmt.low),
                "+",
                "}",
                "%",
              ],
          isIntLiteral(stmt.increment, 1n)
            ? []
            : [emitExpr(stmt.increment), "%"],
          "{",
          ":",
          emitExpr(stmt.variable),
          ";",
          emitMultiExpr(stmt.body, stmt),
          "}",
          "%",
        ];
```
This handles a negative low and/or high bound. Negative increments function as intended, or at least in the same way as Python. If this is undesired behavior it should probably be impossible to use a negative step regardless of lang. This section of new code:
```
emitExpr(stmt.high),
emitExpr(stmt.low),
"-",
```
should emit a `sub` polyGolfOp acting on high and low, or whatever the best way is to enable the subtraction to be simplified, I'm not sure how to go about that though.
